/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "secondary-container": "#d9dff5",
        "on-primary-container": "#dad7ff",
        "tertiary-fixed-dim": "#bdc7d8",
        surface: "#f8f9fa",
        "tertiary-container": "#57616f",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#404758",
        "on-surface-variant": "#464555",
        "outline-variant": "#c7c4d8",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#3e4755",
        "on-secondary": "#ffffff",
        primary: "#3525cd",
        "on-primary-fixed-variant": "#3323cc",
        "surface-bright": "#f8f9fa",
        "surface-tint": "#4d44e3",
        "inverse-on-surface": "#f0f1f2",
        secondary: "#575e70",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-secondary-fixed": "#141b2b",
        "on-primary-fixed": "#0f0069",
        "on-secondary-container": "#5c6274",
        "primary-fixed": "#e2dfff",
        "primary-container": "#4f46e5",
        "inverse-primary": "#c3c0ff",
        "tertiary-fixed": "#d9e3f4",
        tertiary: "#3f4957",
        "surface-variant": "#e1e3e4",
        "surface-container": "#edeeef",
        outline: "#777587",
        "secondary-fixed-dim": "#c0c6db",
        "primary-fixed-dim": "#c3c0ff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#121c28",
        error: "#ba1a1a",
        "on-background": "#191c1d",
        "inverse-surface": "#2e3132",
        "secondary-fixed": "#dce2f7",
        "on-tertiary-container": "#d2dced",
        "error-container": "#ffdad6",
        background: "#f8f9fa",
        "on-surface": "#191c1d",
        "surface-dim": "#d9dadb",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        unit: "4px",
        "container-max": "1280px",
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-room-code": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "code-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-room-code": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
